### ISSUE TITLE
Edit to DockerCompose

### ISSUE THREAD

**Issue by globalenigma** [DesktopContainers/easytag#1]
Could you please edit the following line in your compose file:

 && echo "easytag \$*" >> /usr/local/bin/bin/ssh-app.sh \
to read:
 && echo "easytag \$*" >> /usr/local/bin/ssh-app.sh \

Once I modify that line I am able to open EASYTAG over ssh

**Comment by MarvAmBass** [comment]
hi there, good eye! thanks I totally missed that one
